### ISSUE TITLE
Missing patterns in injectFaviconMarkups

### ISSUE THREAD

**Issue by pdugas** [RealFaviconGenerator/rfg-api#11]
I had to add the following entries to the `defaultRemove` array in the `injectFaviconMarkups` function to make this work for me.  I was getting extra lines every time I built my project.

      'link[rel="mask-icon"]',
      'meta[name="apple-mobile-web-app-title"]',
      'meta[name="application-name"]',

I'm using the API via grunt-real-favicon which does not have a mechanism to pass the `opts.remove` into the call.  I'll report this issue there as well.

**Comment by phbernard** [comment]
Please see https://github.com/RealFaviconGenerator/rfg-api/pull/17#issuecomment-581801771
