### ISSUE TITLE
Replace only relevant markups

### ISSUE THREAD

**Issue by phbernard** [RealFaviconGenerator/rfg-api#4]
Currently, the module removes all favicon-related markups (expected to be replaced by the markups got from RFG).

It should be smarter. It should first inspect the markups returned by RFG, and replace only what is needed. For example, it should replace the `og:image` meta markup only if RFG returned one. Else, the existing meta is perfectly fine and shouldn't be affected.

Reported here: https://github.com/RealFaviconGenerator/grunt-real-favicon/issues/24

**Comment by nhoizey** [comment]
Thanks!

**Comment by pavle-goloskokovic** [comment]
Happens for me too, _og:image_ should not be in the default removes, it should be removed only if it is replaced...
https://github.com/RealFaviconGenerator/rfg-api/blob/master/index.js#L86

**Comment by phbernard** [comment]
Today I added the `keep` option. You can do:

```
injectFaviconMarkups(someContent, someMarkups, 
    { keep: 'meta[property="og:image"]' }, function() {...});
```

This is clearly not the fix for this issue, but at least it can serve as a workaround.

It's already usable with the Gulp plugin. However, I didn't updated the Grunt plugin yet (it always passes an empty hash).

**Comment by nhoizey** [comment]
I'll wait for the Grunt plugin, then… ;-)

https://github.com/esviji/esviji/issues/150

**Comment by phbernard** [comment]
I was reported the issue again and thought of a [better solution, based on the API](https://github.com/RealFaviconGenerator/realfavicongenerator/issues/233).

**Comment by phbernard** [comment]
The API was updated, so the fix in rfg-api side becomes possible. See https://realfavicongenerator.net/api/interactive_api#overlapping_markups

**Comment by phbernard** [comment]
This issue should have been closed long ago. It is possible to take advantage of `overlapping_markups`. For an example of this, see https://github.com/RealFaviconGenerator/grunt-real-favicon/blob/master/tasks/real_favicon.js#L156
