### ISSUE TITLE
Why are you removing og:image from meta tags?

### ISSUE THREAD

**Issue by Chosko** [RealFaviconGenerator/rfg-api#7]
I got a headache to understand what was removing my meta tag from index.html

**Comment by phbernard** [comment]
Sorry about this :(

There is an explanation, yet this is still a bug: #4 . There is also a [workaround](https://github.com/RealFaviconGenerator/rfg-api/issues/4#issuecomment-173354699).

I also entered https://github.com/RealFaviconGenerator/realfavicongenerator/issues/233 as the right solution to this problem.

**Comment by Chosko** [comment]
Thanks :)
