### ISSUE TITLE
Use Promises

### ISSUE THREAD

**Issue by markhalliwell** [RealFaviconGenerator/rfg-api#9]
This project doesn't really have a lot of "callback hell" like the grunt project does, but it would certainly make things a lot easier all around if this project also used Promises.

X-ref: https://github.com/RealFaviconGenerator/grunt-real-favicon/issues/35

**Comment by phbernard** [comment]
Sorry for not answering your message.

I won't implement promises in a near future. But for the record, I will gladly merge a PR which includes dedicated tests.
